import express, { Request, Response } from 'express';
import type { Express } from 'express';
import mongoose from 'mongoose';
import { createServer } from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import dotenv from 'dotenv';
import multer from 'multer';
import path from 'path';
import fs from 'fs'; 
import { User } from './models/User';
import { Appointment } from './models/Appointment';
import { TimetableBlock } from './models/TimetableBlock';
import { AvailabilityRule } from './models/AvailabilityRule';
import { Notification } from './models/Notification';
import { AuditLog } from './models/AuditLog';
import { Message } from './models/Message';
import { AcademicRequest } from './models/AcademicRequest';
import { connectMongo } from './db';
import * as XLSX from 'xlsx';
import Papa from 'papaparse';
import pdf from 'pdf-parse';